SelectClient:SelectClient.c
	gcc $^ -o $@
SelectSever:SelectSever.c
	gcc $^ -o $@
SelectIn:SelectIn.c
	gcc $^ -o $@
dup2:dup2.c
	gcc $^ -o $@
dup:dup.c
	gcc $^ -o $@
NonBlockIO:NonBlockIO.c
	gcc $^ -o $@
