pool:pool.cpp
	g++ -g $^ -o $@ -pthread
rwlock:rwlock.c
	gcc $^ -o $@ -pthread
pcsem:sem.cpp
	g++ -g $^ -o $@ -pthread
sem:sem.c
	gcc -g $^ -o $@ -pthread
pandc:pandc.cpp
	g++ -g $^ -o $@ -pthread
cond:cond.c
	gcc -g $^ -o $@ -pthread
mutex:mutex.c
	gcc $^ -o $@ -pthread
term:term.c
	gcc $^ -o $@ -pthread
creat:creat.c
	gcc $^ -o $@ -pthread
