block:block.c
	gcc -g $^ -o $@
sigchild:sigchild.c
	gcc -g $^ -o $@
volatile:volatile.c
	gcc -g $^ -o $@
compete:compete.c
	gcc -g $^ -o $@
sleep:sleep.c
	gcc -g $^ -o $@
mask:mask.c
	gcc -g $^ -o $@
signal:signal.c
	gcc -g $^ -o $@
core:core.c
	gcc -g $^ -o $@
create:create.c
	gcc $^ -o $@
